spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nss@viit.ac.in
    password: placeholdersetme
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    url: jdbc:postgresql://ep-autumn-hill-ao8yoixr-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_uN7xk5JDMtai
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.nssplatform: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

server:
  servlet:
    session:
      cookie:
        secure: true
