spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nssdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.nssplatform: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

server:
  servlet:
    session:
      cookie:
        secure: true
